### ISSUE TITLE
[bug][epub] ImportError: libQt5Core.so.5 when build epub

### ISSUE THREAD

**Issue by sketchmind** [appotry/docker-gitbook#10]
Raise ImportError: libQt5Core.so.5 when use gitbook epub to build epub,log as follow:

```
Traceback (most recent call last):
  File "/usr/bin/ebook-convert", line 20, in <module>
    sys.exit(main())
  File "/usr/lib/calibre/calibre/ebooks/conversion/cli.py", line 401, in main
    plumber.run()
  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1274, in run
    self.output_plugin.convert(self.oeb, self.output, self.input_plugin,
  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/epub_output.py", line 203, in convert
    from calibre.ebooks.oeb.transforms.split import Split
  File "/usr/lib/calibre/calibre/ebooks/oeb/transforms/split.py", line 22, in <module>
    from calibre.ebooks.oeb.polish.split import do_split
  File "/usr/lib/calibre/calibre/ebooks/oeb/polish/split.py", line 13, in <module>
    from calibre.ebooks.oeb.polish.toc import node_from_loc
  File "/usr/lib/calibre/calibre/ebooks/oeb/polish/toc.py", line 22, in <module>
    from calibre.ebooks.oeb.polish.opf import set_guide_item, get_book_language
  File "/usr/lib/calibre/calibre/ebooks/oeb/polish/opf.py", line 10, in <module>
    from calibre.ebooks.oeb.polish.container import OPF_NAMESPACES
  File "/usr/lib/calibre/calibre/ebooks/oeb/polish/container.py", line 37, in <module>
    from calibre.ebooks.mobi.tweak import set_cover
  File "/usr/lib/calibre/calibre/ebooks/mobi/tweak.py", line 13, in <module>
    from calibre.ebooks.mobi.reader.mobi6 import MobiReader
  File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi6.py", line 24, in <module>
    from calibre.utils.img import save_cover_data_to, gif_data_to_png_data, AnimatedGIF
  File "/usr/lib/calibre/calibre/utils/img.py", line 14, in <module>
    from PyQt5.QtCore import QBuffer, QByteArray, Qt, QIODevice
ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

**Comment by appotry** [comment]
test ok

```
root@7c895eea6ecd:/gitbook# gitbook epub .
info: 30 plugins are installed 
info: 19 explicitly listed 
info: loading plugin "search-plus"... OK 
info: loading plugin "pageview-count"... OK 
info: loading plugin "splitter"... OK 
info: loading plugin "popup"... OK 
info: loading plugin "sectionx"... OK 
info: loading plugin "hide-element"... OK 
info: loading plugin "tbfed-pagefooter"... OK 
info: loading plugin "prism"... OK 
info: loading plugin "sharing-plus"... OK 
info: loading plugin "expandable-chapters"... OK 
info: loading plugin "chapter-fold"... OK 
info: loading plugin "accordion"... OK 
info: loading plugin "back-to-top-button"... OK 
info: loading plugin "sitemap-general"... OK 
info: loading plugin "copy-code-button"... OK 
info: loading plugin "expandable-chapters-small"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-fexa"... OK 
info: loading plugin "theme-default"... OK 
info: found 10 pages 
info: found 1 asset files 
warn: "options" property is deprecated, use config.get(key) instead 
warn: "options.generator" property is deprecated, use "output.name" instead 
info: >> generation finished with success in 15.0s ! 
info: >> 1 file(s) generated 
```

it is possible that a GitBook plugin is causing the error @sketchmind
